DOMAIN                  = 'irrigationprogram'
SWITCH_ID_FORMAT        = 'switch' + '.{}'

ATTR_RAIN_SENSOR        = 'rain_sensor'
ATTR_DISABLE_IRRIGATION = 'disable_irrigation'
ATTR_IRRIGATION_ON      = 'irrigation_on'
ATTR_START              = 'start_time'
ATTR_IGNORE_RAIN_SENSOR = 'ignore_rain_sensor'
ATTR_RUN_DAYS           = 'run_days'
ATTR_RUN_FREQ           = 'run_freq'
ATTR_EVAL               = 'eval'
ATTR_FRIENDLY_NAME      = 'friendly_name'
ATTR_NAME               = 'name'
ATTR_REMAINING          = 'remaining'
ATTR_REPEAT             = 'repeat'
ATTR_RUNTIME            = 'runtime'
ATTR_SWITCH             = 'switch_entity'
ATTR_WAIT               = 'wait'
ATTR_WATER              = 'water'
ATTR_ZONES              = 'zones'
ATTR_ZONE               = 'zone'
ATTR_ICON               = 'icon'
ATTR_ICON_WATER         = 'icon_on'
ATTR_ICON_WAIT          = 'icon_wait'
ATTR_ICON_OFF           = 'icon_off'
ATTR_PROGRAMS           = 'programs'
CONST_ENTITY            = 'entity_id'
CONST_SWITCH            = 'switch'


DFLT_ICON               = 'mdi:fountain'
